package day8

import (
	"fmt"
	"os"
	"time"
)

//Generated by AoC helper tool for day 8 🎄
//In order to get started, extend main.go so it discovers and runs this file as well

type Day8Solver struct{}

func (d Day8Solver) Solve(filename string, answerChan chan int, doneChan chan bool, errorChan chan error) {
	start := time.Now()

	defer close(answerChan)
	defer close(errorChan)
	defer close(doneChan)
	file, err := os.Open(filename)

	if err != nil {
		errorChan <- err
	}

	defer file.Close()

	//scanner := bufio.NewScanner(file)

	answerChan <- 0
	answerChan <- 0

	end := time.Now()
	elapsed := end.Sub(start)
	fmt.Printf("\n\n⏱️ Execution took %v time! ⏱️\n\n", elapsed)

	doneChan <- true
}
